More CI preparation

diff --git a/packages/app/justfile b/packages/app/justfile
--- a/packages/app/justfile
+++ b/packages/app/justfile
@@ -2,28 +2,42 @@ set dotenv-load
 set positional-arguments
 
 build platform profile:
+  eas build --platform {{platform}} --local --profile {{profile}}
+
+submit platform profile path:
+  eas submit --platform {{platform}} --profile {{profile}} --path {{path}}
+
+push platform profile:
   #!/bin/bash
-  # eas build --platform {{platform}} --local --profile {{profile}}
-  # Exit immediately if there are uncommitted changes
   if [[ -n "$(git status --porcelain)" ]]; then
     echo "Error: You have uncommitted changes. Please commit or stash your changes before running this script."
     exit 1
   fi
 
-  # Find the highest version code from "app-release/<version code>" tags
+  if git describe --tags --exact-match &> /dev/null | grep -q '{{platform}}-release/'; then
+    echo "Error: Current commit is already tagged. Create a new commit."
+    exit 1
+  fi
+
+  mkdir -p build/{{platform}}
+
   version_codes=()
-  for tag in $(git tag --list 'app-release/*'); do
-    version=$(echo $tag | sed 's/app-release\///g')
+  for tag in $(git tag --list '{{platform}}-release/*'); do
+    version=$(echo $tag | sed 's/{{platform}}-release\///g')
     version_codes+=($version)
   done
   current_version=$(($(printf '%d\n' "${version_codes[@]}" | sort -n | tail -1) + 1))
 
-  command_to_run="echo 'New version code: $current_version'"
-  $command_to_run
+  echo "New version code: $current_version"
+
+  git tag "{{platform}}-release/$current_version"
+
+  output_path="build/{{platform}}/{{profile}}-$current_version"
+
+  VERSION_CODE=$current_version eas build --platform {{platform}} --local --profile {{profile}} --output $output_path
 
   echo "Successfully built version $current_version"
-  # Tag the current commit with the new version code
-  # git tag "app-release/$current_version"
 
-submit platform path:
-  eas submit --platform {{platform}} --path {{path}}
+  eas submit --platform {{platform}} --profile {{profile}} --path $output_path
+
+  echo "Successfully pushed {{platform}} version $current_version with profile {{profile}}"
